# Generated by Django 4.2.5 on 2023-09-19 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
